### ISSUE TITLE
Unable to connect to Waypoint server

### ISSUE THREAD

**Issue by ajinkya6** [hashicorp-dev-advocates/terraform-provider-waypoint#33]
### Terraform Version
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp-dev-advocates/waypoint v0.3.0
+ provider registry.terraform.io/hashicorp/azurerm v3.32.0

### Expected Behavior
`terraform apply` should create `waypoint_project` resource 

### Actual Behavior
after doing `terraform apply` I get Error:

```
╷
│ Error: unable to connect to Waypoint server
│ 
│   with provider["registry.terraform.io/hashicorp-dev-advocates/waypoint"],
│   on providers.tf line 24, in provider "waypoint":
│   24: provider "waypoint" {
```

### Steps to Reproduce
I have vault up and running on Azure on "https://hashicorp-waypoint-ui-External-ip" . however I am unable to use the waypoint provider. Here is my providers.tf file

providers.tf file:
```
# azurermversion 3.31.0
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.32.0"
    }
    waypoint = {
      source = "hashicorp-dev-advocates/waypoint"
      version = "0.3.0"
    }
  }
}

provider "azurerm" {
  features {}
} 

provider "waypoint" {
  waypoint_addr = "https://<hashicorp-waypoint-ui-External-ip>"
  token         = "vghj...8cwvbn"
}

```

`terraform apply`  should not give any error . But I am getting error:

```
╷
│ Error: unable to connect to Waypoint server
│ 
│   with provider["registry.terraform.io/hashicorp-dev-advocates/waypoint"],
│   on providers.tf line 24, in provider "waypoint":
│   24: provider "waypoint" {
```
How do I resolve this , as I am able to connect to waypoint using same token on "https://hashicorp-waypoint-ui-External-ip" on Google Chrome browser, is there something I am missing in Terraform ?

cc @devops-rob

**Comment by ajinkya6** [comment]
cc @nicholasjackson @ksatirli

**Comment by devops-rob** [comment]
Hi @ajinkya6 Is the waypoint server self hosted or is it HCP?

**Comment by devops-rob** [comment]
I think removing the transport protocol might be the trick. So "https://hashicorp-waypoint-ui-External-ip" => "hashicorp-waypoint-ui-External-ip"

**Comment by ajinkya6** [comment]
Hi @devops-rob  

Thanks that did the trick I replaced with `hashicorp-waypoint-ui-External-ip:9701` . Just curious why didnt `https`  work  ?

**Comment by devops-rob** [comment]
No Probs. Glad it's working now. Under the hood Waypoint using using a gRPC API so the interactions within the provider aren't using a Restful approach. I'll close the issue but please feel free to re-open it if anything else related happens. Thanks again :-)
